.PHONY: help install-uv setup check test-core test-molecules test-all test \
	docs-build-api docs-sync-api docs-serve docs-build build-core build-molecules \
	build check-all clean

help: ## Show this help message
	@awk -F':.*?## ' '/^[a-zA-Z0-9_-]+:.*## / {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install-uv: ## Install uv package manager
	@echo "Installing uv..."
	curl -LsSf https://astral.sh/uv/install.sh | sh

setup: ## Initialize environment and install dependencies
	uv sync --all-packages --group dev
	uv run pre-commit install

check: ## Run pre-commit checks using uv
	uv run pre-commit run --all-files --show-diff-on-failure

test-core: ## Run tests owned by the activelearning core package
	uv run pytest tests

test-molecules: ## Run tests owned by the activelearning-molecules package
	uv run pytest applications/molecules/tests

test-all: ## Run core and application tests
	uv run pytest tests applications/molecules/tests

test: test-all ## Run all workspace tests (core and applications)

build-core: ## Build the activelearning distribution
	uv build --package activelearning

build-molecules: ## Build the activelearning-molecules distribution
	uv build --package activelearning-molecules

build: build-core build-molecules ## Build every workspace distribution

check-all: check test-all build ## Run checks, all tests, and both package builds

docs-build-api: ## Build the Sphinx API reference into site/reference/
	mkdir -p site
	rm -rf docs_api/_build site/reference
	find docs_api/source -mindepth 1 ! -name index.rst -exec rm -rf {} +
	uv run sphinx-build -E -a -c docs_api -b dirhtml -d docs_api/_build/doctrees docs_api/source site/reference

docs-serve: docs-build ## Serve the built docs locally at http://127.0.0.1:8000
	uv run python -m http.server 8000 -d site

docs-build: ## Build the full docs site
	rm -rf site
	uv run zensical build --config-file zensical.toml --clean
	$(MAKE) docs-build-api

clean: ## Clean autogenerated files and uv cache
	rm -rf dist .venv .pytest_cache
	rm -rf docs_api/_build site
	find docs_api/source -mindepth 1 ! -name index.rst -exec rm -rf {} +
	find . -type f -name "*.DS_Store" -delete
	find . -type f -name "*.py[co]" -delete
	find . -type d -name "__pycache__" -delete
	uv clean
