.PHONY: help install-uv setup check test clean

help: ## Show this help message
	@awk -F':.*?## ' '/^[a-zA-Z0-9_-]+:.*## / {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install-uv: ## Install uv package manager
	@echo "Installing uv..."
	curl -LsSf https://astral.sh/uv/install.sh | sh

setup: ## Initialize environment and install dependencies
	uv sync
	uv run pre-commit install

check: ## Run pre-commit checks using uv
	uv run pre-commit run --all-files --show-diff-on-failure

test: ## Run tests within the uv environment
	uv run pytest

clean: ## Clean autogenerated files and uv cache
	rm -rf dist .venv .pytest_cache
	find . -type f -name "*.DS_Store" -delete
	find . -type f -name "*.py[co]" -delete
	find . -type d -name "__pycache__" -delete
	uv clean
