.PHONY: help install-uv setup check test docs-build-api docs-sync-api docs-serve docs-build clean

help: ## Show this help message
	@awk -F':.*?## ' '/^[a-zA-Z0-9_-]+:.*## / {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install-uv: ## Install uv package manager
	@echo "Installing uv..."
	curl -LsSf https://astral.sh/uv/install.sh | sh

setup: ## Initialize environment and install dependencies
	uv sync
	uv run pre-commit install

check: ## Run pre-commit checks using uv
	uv run pre-commit run --all-files --show-diff-on-failure

test: ## Run tests within the uv environment
	uv run pytest

docs-build-api: ## Build the Sphinx API reference into site/reference/
	mkdir -p site
	rm -rf docs_api/_build docs_api/source/activelearning site/reference
	uv run sphinx-build -E -a -c docs_api -b dirhtml -d docs_api/_build/doctrees docs_api/source site/reference

docs-serve: docs-build ## Serve the built docs locally at http://127.0.0.1:8000
	uv run python -m http.server 8000 -d site

docs-build: ## Build the full docs site
	rm -rf site
	uv run zensical build --config-file zensical.toml --clean
	$(MAKE) docs-build-api

clean: ## Clean autogenerated files and uv cache
	rm -rf dist .venv .pytest_cache
	rm -rf docs_api/_build docs_api/source/activelearning site
	find . -type f -name "*.DS_Store" -delete
	find . -type f -name "*.py[co]" -delete
	find . -type d -name "__pycache__" -delete
	uv clean
