dataset:
  type: ListDataset
  initial_data:
    path: ${reproduce_paper.initial_data.low}
    x_columns: [x1, x2]
    y_column: y
    fidelity_column: fidelity
    metadata_columns: remaining

acquisition:
  type: QLowerBoundMaxValueEntropy
  candidate_set_spec:
    type: TrainDataCandidateSetSpec

sampler:
  type: HypercubeGridSampler
  bounds: ${reproduce_paper.domain_bounds}
  points_per_dimension: [100, 100]
  fidelities: [1]
  num_samples: ${reproduce_paper.candidate_sample_count}
  use_acquisition_scores: true

oracle:
  type: CensoredSyntheticOracle
  function: branin
  threshold: -134.39
  fidelity_costs:
    1: 0.01
  fidelity_confidences:
    1: 0.1

reproduce_paper:
  method: sf_low_fid
  method_label: SF-GFN-LOW
