dataset:
  type: ListDataset
  initial_data:
    path: ${reproduce_paper.initial_data.multi}
    x_columns: [x1, x2]
    y_column: y
    fidelity_column: fidelity
    metadata_columns: remaining

surrogate:
  type: BoTorchGPSurrogate

acquisition:
  type: QMultiFidelityLowerBoundMaxValueEntropy
  candidate_set_spec:
    type: TrainDataCandidateSetSpec

sampler:
  type: HypercubeGridSampler
  bounds: ${reproduce_paper.domain_bounds}
  points_per_dimension: [100, 100]
  fidelities: [1, 2, 3]
  num_samples: ${reproduce_paper.candidate_sample_count}
  use_acquisition_scores: true

selector:
  type: TopKAcquisitionSelector
  num_samples: 1

oracle:
  type: BraninOracle
  fidelity_costs: ${reproduce_paper.oracle_costs}
  fidelity_confidences: ${reproduce_paper.fidelity_confidences}
