_target_: activelearning.sampler.gflownet.logger_wrapper.RuntimeGFlowNetLoggerWrapper

do:
  online: False
  times: False

project_name: "activelearning"

# Log dir
logdir:
  root: ./logs
  ckpts: ckpts
  overwrite: True
debug: False
lightweight: False
progressbar:
  skip: False
  n_iters_mean: 100
context: "0"
notes: null
entity: null
run_id: null

# Set to True for resuming runs
is_resumed: False

# Name of the run
run_name: null
# Whether the date (and time) should be included in the run name
run_name_date: True
# Whether the job id should be included in the run name
run_name_job: True
