"""Dependency-free constants for the molecules application."""

SELFIES_VOCAB_SMALL: list[str] = [
    "[#Branch1]",
    "[#Branch2]",
    "[#C]",
    "[#N]",
    "[=Branch1]",
    "[=Branch2]",
    "[=C]",
    "[=N]",
    "[=O]",
    "[=Ring1]",
    "[=Ring2]",
    "[=S]",
    "[B]",
    "[Br]",
    "[Branch1]",
    "[Branch2]",
    "[C]",
    "[Cl]",
    "[F]",
    "[NH1]",
    "[N]",
    "[O]",
    "[P]",
    "[Ring1]",
    "[Ring2]",
    "[S]",
]
